VERSION: 1

DATASETS:
  TRAIN: ("carvana_train",)
  TEST: ("carvana_test",)

INPUT:
  MIN_SIZE_TRAIN: (1280,)
  MIN_SIZE_TEST: 1280
  MAX_SIZE_TRAIN: 1918
  MAX_SIZE_TEST: 1918
  FORMAT: "BGR"
  MASK_FORMAT: "bitmask"

MODEL:
  # WEIGHTS: "weights/..."
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  PIXEL_MEAN: [174.392, 176.177, 177.963]
  PIXEL_STD: [59.578, 60.148, 59.305]
  MASK_ON: False
  META_ARCHITECTURE: "RCNN3D"
  BACKBONE:
    NAME: "build_resnet_backbone"
    # FREEZE_AT: 0
  RESNETS:
    # DEPTH: 50
    OUT_FEATURES: ["conv3d"]
  PROPOSAL_GENERATOR:
    NAME: "RPN3D"
    MIN_SIZE: 0
  RPN:
    HEAD_NAME: "RPNHead3D"
    IN_FEATURES: ["conv3d"]
    PRE_NMS_TOPK_TRAIN: 6000
    PRE_NMS_TOPK_TEST: 3000
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 500
  ANCHOR_GENERATOR:
    NAME: "AnchorGenerator3D"
  # ROI_HEADS:
  #   NAME: "StandardROIHeads"
  #   # NAME: "Res5ROIHeads"
  #   BATCH_SIZE_PER_IMAGE: 128
  #   NUM_CLASSES: 1
  #   IN_FEATURES: ["res4"]
  # ROI_MASK_HEAD:
  #   NAME: "MaskRCNNConvUpsampleHead"
  #   NUM_CONV: 4

SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  BASE_LR: 0.001
  MAX_ITER: 1000
  IMS_PER_BATCH: 1
